name: XcodeBuildCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 1_UIViewExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 2_ProtocolDelegateExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 3_TableViewExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 4_MultiCellTableViewExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 5_CollectionVIewExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 6_CustomLayoutCollectionViewExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 7_isEqual&NSCopying -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 8_PageViewControllerExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    - run: xcodebuild clean build -project iosStudy.xcodeproj -scheme 9_LocationManagerExample -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X'
    
